export enum EDbModels {
  COMMUNITY_BUILD = 'CommunityBuild',
  COMMUNITY_CHANNEL = 'CommunityChannel',
  COMMUNITY_GROUP = 'CommunityGroup',
  EVENT = 'Event',
  HACKATHON = 'Hackathon',
  HACKATHON_TEAM = 'HackathonTeam',
  KOMMUNITY = 'Kommunity',
  LAB = 'Lab',
  RAZORPAY_LINKED_ACCOUNT = 'RazorpayLinkedAccount',
  STRIPE_CONNECT_ACCOUNT = 'StripeConnectAccount',
  USER = 'User',
  MAIN_NEWSLETTER = 'MainNewsletter',
  NEWSLETTER = 'Newsletter',
}
